// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGF9rjcgrj-DHAxaew-QdhkER1FP06eMM',
    appId: '1:204719491488:web:51296a8675abda4f323cc5',
    messagingSenderId: '204719491488',
    projectId: 'tbibi-e33ee',
    authDomain: 'tbibi-e33ee.firebaseapp.com',
    storageBucket: 'tbibi-e33ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAVrriFVFKoGMRQvb3VnN4txgsxw9w4ms',
    appId: '1:204719491488:android:b46ca7a41c5e1aca323cc5',
    messagingSenderId: '204719491488',
    projectId: 'tbibi-e33ee',
    storageBucket: 'tbibi-e33ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBczJCFKueYKOLGtrIKZGyO6Ihl7uSI1uM',
    appId: '1:204719491488:ios:cc5f3456f913dcce323cc5',
    messagingSenderId: '204719491488',
    projectId: 'tbibi-e33ee',
    storageBucket: 'tbibi-e33ee.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBczJCFKueYKOLGtrIKZGyO6Ihl7uSI1uM',
    appId: '1:204719491488:ios:cc5f3456f913dcce323cc5',
    messagingSenderId: '204719491488',
    projectId: 'tbibi-e33ee',
    storageBucket: 'tbibi-e33ee.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGF9rjcgrj-DHAxaew-QdhkER1FP06eMM',
    appId: '1:204719491488:web:84ec36413933d83f323cc5',
    messagingSenderId: '204719491488',
    projectId: 'tbibi-e33ee',
    authDomain: 'tbibi-e33ee.firebaseapp.com',
    storageBucket: 'tbibi-e33ee.firebasestorage.app',
  );
}
